In [1]:
import pandas as pd

In [ ]:
pd.show_versions()

# make dataframe

In [7]:
df = pd.DataFrame({'col_a': [1,2,3,4,5], 'col_b': [6,7,8,9,10]})
df

   col_a  col_b
0      1      6
1      2      7
2      3      8
3      4      9
4      5     10

In [9]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[3,4,9,7]])
pd.DataFrame(arr)

   0  1  2  3
0  1  2  3  4
1  5  6  7  8
2  3  4  9  7

In [13]:
pd.DataFrame(np.random.rand(4,8))

,0,1,2,3,4,5,6,7
0,0.019907,0.891385,0.612057,0.909178,0.583271,0.739861,0.790944,0.795901
1,0.246021,0.557056,0.485600,0.178013,0.279151,0.389430,0.524027,0.075866
2,0.685379,0.466598,0.577632,0.391711,0.165114,0.831549,0.966662,0.929910
3,0.383437,0.270891,0.516179,0.719774,0.879263,0.937587,0.603522,0.975671

In [14]:
df.columns=['col_1','col_2']
df

   col_1  col_2
0      1      6
1      2      7
2      3      8
3      4      9
4      5     10

In [15]:
df= df.add_prefix('C')
df

   Ccol_1  Ccol_2
0       1       6
1       2       7
2       3       8
3       4       9
4       5      10