# how to import dataset in pythoon using pandas library file
written by dr. ammar toufail 

date: 6.12.2024  

email: ....

In [ ]:
pip install pandas

In [15]:
import pandas as pd

In [31]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\ad\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ad\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

In [32]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [35]:
df= pd.read_excel("pandas_01_day6.xlsx")

In [36]:
print(df)

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [37]:
df.head()

  Height Weight Favourite Dish
0    5.8    101  Chicken Pulao
1    6.2     92        Biryani
2    5.9     62  Karahi Ghosht
3    5.9     95  Chicken Pulao
4    5.9     55  Chicken Pulao

In [38]:
df.tail()

   Height Weight Favourite Dish
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

In [39]:
df.shape

(87, 3)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          87 non-null     object
 1   Weight          87 non-null     object
 2   Favourite Dish  87 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB